version = 1

[[analyzers]]
name = docker
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    dockerfile_dev,
    dockerfile_prod
  ]

  trusted_registries = [
    my-registry.com,
    docker.io
  ]