FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS mine-service-test

WORKDIR /src
COPY . .
WORKDIR /src/src
RUN dotnet restore "./Mine.Commerce.Service.sln"

WORKDIR /src
COPY /.github/tests/start-test.sh /app/start-test.sh

WORKDIR /app
ENTRYPOINT ["start-test.sh"]